### ISSUE TITLE
I got "no proposals" on autocomplete with "Command error Error: Argument out of range: position"

### ISSUE THREAD

**Issue by kosz78** [axmor/typecs#11]
![2.png](https://bitbucket.org/repo/eRnj8G/images/2068029414-2.png)

```
Command error Error: Argument out of range: position
    at Function.Errors.argumentOutOfRange (/home/apare/.eclipse/org.eclipse.platform_4.4.0_1473617060_linux_gtk_x86_64/plugins/com.axmor.eclipse.typescript.core_1.5.1.201405141411/lib/bridge/ts_1.0.0/typescriptServices.js:1253:20)
    at SourceUnitSyntax.SyntaxNode.findToken (/home/apare/.eclipse/org.eclipse.platform_4.4.0_1473617060_linux_gtk_x86_64/plugins/com.axmor.eclipse.typescript.core_1.5.1.201405141411/lib/bridge/ts_1.0.0/typescriptServices.js:9800:41)
    at Object.isEntirelyInsideComment (/home/apare/.eclipse/org.eclipse.platform_4.4.0_1473617060_linux_gtk_x86_64/plugins/com.axmor.eclipse.typescript.core_1.5.1.201405141411/lib/bridge/ts_1.0.0/typescriptServices.js:8462:46)
    at Function.CompletionHelpers.isCompletionListBlocker (/home/apare/.eclipse/org.eclipse.platform_4.4.0_1473617060_linux_gtk_x86_64/plugins/com.axmor.eclipse.typescript.core_1.5.1.201405141411/lib/bridge/ts_1.0.0/typescriptServices.js:64801:42)
    at LanguageService.getCompletionsAtPosition (/home/apare/.eclipse/org.eclipse.platform_4.4.0_1473617060_linux_gtk_x86_64/plugins/com.axmor.eclipse.typescript.core_1.5.1.201405141411/lib/bridge/ts_1.0.0/typescriptServices.js:66371:48)
    at Object.exports.getCompletionsAtPosition (/home/apare/.eclipse/org.eclipse.platform_4.4.0_1473617060_linux_gtk_x86_64/plugins/com.axmor.eclipse.typescript.core_1.5.1.201405141411/lib/bridge/ts_1.0.0/ets_service.js:34:13)
    at Socket.<anonymous> (/home/apare/.eclipse/org.eclipse.platform_4.4.0_1473617060_linux_gtk_x86_64/plugins/com.axmor.eclipse.typescript.core_1.5.1.201405141411/lib/bridge/bridge.js:61:43)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

---
- Bitbucket: https://bitbucket.org/axmor/typecs/issue/11
- Originally reported by: Alexandre Paré
- Originally created at: 2014-08-23T07:39:40.180

**Comment by kosz78** [comment]
_From Konstantin Zaitcev on 2014-08-23 17:41:20+00:00_

fixed #11: problem with auto complete

→ <<cset 1e20ebf8a149>>
