### ISSUE TITLE
Local history

### ISSUE THREAD

**Issue by kosz78** [axmor/typecs#13]
NPE occur in a local history dialog.
1. Replace With > Local History...
2. Double click date,

```
java.lang.NullPointerException
    at com.axmor.eclipse.typescript.editor.TypeScriptEditorConfiguration.getContentAssistant(TypeScriptEditorConfiguration.java:177)
    at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:464)
    at com.axmor.eclipse.typescript.editor.compare.TypeScriptMergeViewer.configureTextViewer(TypeScriptMergeViewer.java:38)
    at org.eclipse.compare.contentmergeviewer.TextMergeViewer.configureSourceViewer(TextMergeViewer.java:2938)
    at org.eclipse.compare.contentmergeviewer.TextMergeViewer.updateContent(TextMergeViewer.java:2879)
    at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.internalRefresh(ContentMergeViewer.java:743)
    at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.inputChanged(ContentMergeViewer.java:643)
    at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:280)
    at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:277)
    at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:158)
    at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:845)
    at org.eclipse.compare.CompareEditorInput.access$8(CompareEditorInput.java:843)
    at org.eclipse.compare.CompareEditorInput$11.run(CompareEditorInput.java:786)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:773)
    at org.eclipse.compare.CompareEditorInput.access$3(CompareEditorInput.java:772)
    at org.eclipse.compare.CompareEditorInput$5.open(CompareEditorInput.java:658)
    at org.eclipse.compare.CompareViewerPane.open(CompareViewerPane.java:325)
    at org.eclipse.team.ui.PageCompareEditorInput$1.open(PageCompareEditorInput.java:83)
    at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:866)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:864)
    at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1152)
    at org.eclipse.jface.viewers.StructuredViewer$6.handleOpen(StructuredViewer.java:1256)
    at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:275)
    at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:269)
    at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:309)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
    at org.eclipse.jface.window.Window.open(Window.java:802)
    at org.eclipse.compare.internal.CompareDialog.open(CompareDialog.java:196)
    at org.eclipse.compare.internal.CompareUIPlugin$4.run(CompareUIPlugin.java:1391)
    at org.eclipse.compare.internal.CompareUIPlugin.syncExec(CompareUIPlugin.java:1401)
    at org.eclipse.compare.internal.CompareUIPlugin.internalOpenDialog(CompareUIPlugin.java:1394)
    at org.eclipse.compare.internal.CompareUIPlugin.openCompareDialog(CompareUIPlugin.java:575)
    at org.eclipse.compare.CompareUI.openCompareDialog(CompareUI.java:211)
    at org.eclipse.team.internal.ui.history.ReplaceLocalHistory.showCompareInDialog(ReplaceLocalHistory.java:66)
    at org.eclipse.team.internal.ui.history.ReplaceLocalHistory.access$0(ReplaceLocalHistory.java:40)
    at org.eclipse.team.internal.ui.history.ReplaceLocalHistory$1.run(ReplaceLocalHistory.java:34)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

```

---
- Bitbucket: https://bitbucket.org/axmor/typecs/issue/13
- Originally reported by: Kensuke Matsuzaki
- Originally created at: 2014-09-11T10:27:47.947

**Comment by kosz78** [comment]
_From Konstantin Zaitcev on 2014-12-09 14:02:24+00:00_

It is possible already fixed, cannot reproduce on the latest build
