### ISSUE TITLE
Console is flooded with exception after installation and plugin does not seem to work

### ISSUE THREAD

**Issue by kosz78** [axmor/typecs#16]
I just installed the plugin into my Eclipse. After installation I get the following exception stack in my console. Seems to be an endless loop. Eclipse was opened with the Type Script perspective but also file associations does not work although they are defined in the eclipse settings.

```
Command error TypeError: Cannot read property 'version' of null
at HostCache.getVersion (D:\ide\eclipse-SDK-4.3.0-win32-x86_64\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:64577:97)
at SyntaxTreeCache.getCurrentFileSyntaxTree (D:\ide\eclipse-SDK-4.3.0-win32-x86_64\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:64616:47)
at LanguageService.getSyntaxTree (D:\ide\eclipse-SDK-4.3.0-win32-x86_64\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:67083:46)
at LanguageService.getScriptLexicalStructure (D:\ide\eclipse-SDK-4.3.0-win32-x86_64\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:67074:39)
at Object.exports.getScriptLexicalStructure (D:\ide\eclipse-SDK-4.3.0-win32-x86_64\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\ets_service.js:29:13)
at Socket.<anonymous> (D:\ide\eclipse-SDK-4.3.0-win32-x86_64\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\bridge.js:57:55)
at Socket.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:919:16
at process._tickCallback (node.js:419:13)
```

Eclipse:
Version: Kepler Service Release 2
Build id: 20140224-0627

nodejs:
0.10.28 (x64)

OS:
Win 7

---
- Bitbucket: https://bitbucket.org/axmor/typecs/issue/16
- Originally reported by: Michael Ernst
- Originally created at: 2014-10-13T17:12:11.471

**Comment by kosz78** [comment]
_From Pavel Kudrin on 2014-10-17 09:33:26+00:00_

fixed. commit #99

**Comment by kosz78** [comment]
_From Konstantin Zaitcev on 2014-10-22 02:51:02+00:00_

Issue #18 was marked as a duplicate of this issue.
