### ISSUE TITLE
Command error TypeError: Cannot read property 'version' of null

### ISSUE THREAD

**Issue by kosz78** [axmor/typecs#18]
Command error TypeError: Cannot read property 'version' of null
    at HostCache.getVersion (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:64577:97)
    at SyntaxTreeCache.getCurrentFileSyntaxTree (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:64616:47)
    at LanguageService.getSyntaxTree (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:67083:46)
    at LanguageService.getScriptLexicalStructure (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:67074:39)
    at Object.exports.getScriptLexicalStructure (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\ets_service.js:29:13)
    at Socket.<anonymous> (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\bridge.js:57:55)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
Command error TypeError: Cannot read property 'version' of null
    at HostCache.getVersion (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:64577:97)
    at SyntaxTreeCache.getCurrentFileSyntaxTree (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:64616:47)
    at LanguageService.getSyntaxTree (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:67083:46)
    at LanguageService.getScriptLexicalStructure (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\typescriptServices.js:67074:39)
    at Object.exports.getScriptLexicalStructure (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\ts_1.0\ets_service.js:29:13)
    at Socket.<anonymous> (C:\eclipse\plugins\com.axmor.eclipse.typescript.core_2.0.0.201409230908\lib\bridge\bridge.js:57:55)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

I have installed your tool and both time I am getting this error repeating over and over in my TS Bridge Console.  

---
- Bitbucket: https://bitbucket.org/axmor/typecs/issue/18
- Originally reported by: Travis Thomas
- Originally created at: 2014-10-21T21:04:31.768

**Comment by kosz78** [comment]
_From Travis Thomas on 2014-10-21 19:07:05+00:00_

Restarting my computer seems to have helped for the moment but I think I did a restart earlier and the issue returned.

**Comment by kosz78** [comment]
_From Travis Thomas on 2014-10-21 21:22:01+00:00_

New->File->SomeFILE.ts After adding a new file to my project this error seemed to start firing.  Closing and reopening Eclipse normally fixes it.  I'm thinking the one time where I restarted I must have done something to trigger it right after restarting Eclipse.

**Comment by kosz78** [comment]
_From Konstantin Zaitcev on 2014-10-22 02:50:50+00:00_

We have fixed this problem in https://bitbucket.org/axmor/typecs/issue/16/console-is-flooded-with-exception-after the updated version of the plugin will be available a soon

**Comment by kosz78** [comment]
_From Konstantin Zaitcev on 2014-10-22 02:51:02+00:00_

Duplicate of #16.

**Comment by kosz78** [comment]
_From Konstantin Zaitcev on 2014-10-23 18:09:51+00:00_

@hurtlerusa we just published TypEcs update with hotfixes could you please update and check

**Comment by kosz78** [comment]
_From Travis Thomas on 2014-10-23 19:53:01+00:00_

I believe with the older version I could add .ts files.
![noTSfileadd.png](https://bitbucket.org/repo/eRnj8G/images/2136848105-noTSfileadd.png)

Also it seems that syntax highlighting is not working.

**Comment by kosz78** [comment]
_From Travis Thomas on 2014-10-24 13:06:34+00:00_

Syntax highlighting fixed by Window->Preferences->General->Editors->File Association->*.ts had to set TypeScript Editor to default.  Was set to Text Editor I believe which has a note (locked by 'TypeScript source file' content type)
