### ISSUE TITLE
NPE when trying to search constructor references

### ISSUE THREAD

**Issue by kosz78** [axmor/typecs#27]
Problem:

Trying to search constructor references of a TypeScript class fails with Exception:

java.lang.NullPointerException

```
at com.axmor.eclipse.typescript.editor.search.TypeScriptSearchQuery.run(TypeScriptSearchQuery.java:111)

at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)

at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Steps to reproduce:

1) open/create TypeScript class, such as example on http://www.typescriptlang.org/Playground (after selecting classes from dropdown)

2) select constructor

3) press Ctrl+Shift+G (or right click and "References" -> "Workspace")

4) error message is shown. Expecting Search results similar to searching method or field references.

---
- Bitbucket: https://bitbucket.org/axmor/typecs/issue/27
- Originally reported by: [atsu85](https://bitbucket.org/atsu85)
- Originally created at: 2014-12-02T19:26:12.463

**Comment by kosz78** [comment]
_From [atsu85](https://bitbucket.org/atsu85) on 2014-12-02 19:27:33+00:00_

NPE comes from here:
https://bitbucket.org/axmor/typecs/src/6ab855f1ec7c6e4638db58ddb8c6c67ba35de79a/src/com.axmor.eclipse.typescript.editor/src/com/axmor/eclipse/typescript/editor/search/TypeScriptSearchQuery.java?at=default#cl-111

and is caused by empty object returned from JS bridge call to function getOccurrencesAtPosition:

https://bitbucket.org/axmor/typecs/src/6ab855f1ec7c6e4638db58ddb8c6c67ba35de79a/src/com.axmor.eclipse.typescript.core/src/com/axmor/eclipse/typescript/core/internal/TypeScriptAPIImpl.java?at=default#cl-232

getOccurrencesAtPosition function is implemented in this file:
https://bitbucket.org/axmor/typecs/src/6ab855f1ec7c6e4638db58ddb8c6c67ba35de79a/src/com.axmor.eclipse.typescript.core/lib/bridge/ts_1.3/typescriptServices.js?at=default

**Comment by kosz78** [comment]
_From Konstantin Zaitcev on 2014-12-15 18:10:27+00:00_

Resolved in the latest dev build

**Comment by kosz78** [comment]
_From [atsu85](https://bitbucket.org/atsu85) on 2014-12-24 12:14:12+00:00_

Thank You for fixing the NPE. I hoped that instead of preventing NPE You could also make searching constructor references work, but i guess currently typescriptServices.js doesn't index constructors?
