### ISSUE TITLE
Command error Error: not yet implemented at StringScriptSnapshot.getChangeRange

### ISSUE THREAD

**Issue by mustajarvi** [axmor/typecs#37]
I'm using the nightly build from February 11th so I don't know if it's appropriate to file issues, but I'm getting lots of error output in the Eclipse console. 

```
Command error Error: not yet implemented
    at StringScriptSnapshot.getChangeRange (/home/rikard/eclipse-4.4/plugins/com.axmor.eclipse.typescript.core_3.0.0.201502111825/lib/bridge/ts/typescriptServices.js:21502:23)
    at HostCache.getChangeRange (/home/rikard/eclipse-4.4/plugins/com.axmor.eclipse.typescript.core_3.0.0.201502111825/lib/bridge/ts/typescriptServices.js:22400:35)
    at synchronizeHostData (/home/rikard/eclipse-4.4/plugins/com.axmor.eclipse.typescript.core_3.0.0.201502111825/lib/bridge/ts/typescriptServices.js:22824:53)
    at Object.getQuickInfoAtPosition (/home/rikard/eclipse-4.4/plugins/com.axmor.eclipse.typescript.core_3.0.0.201502111825/lib/bridge/ts/typescriptServices.js:23594:13)
    at Object.exports.getSignatureAtPosition (/home/rikard/eclipse-4.4/plugins/com.axmor.eclipse.typescript.core_3.0.0.201502111825/lib/bridge/ts/ets_service.js:39:13)
    at Socket.<anonymous> (/home/rikard/eclipse-4.4/plugins/com.axmor.eclipse.typescript.core_3.0.0.201502111825/lib/bridge/bridge.js:156:55)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```

I haven't used TypEcs before, but apart from the error messages everything seems to work fine.

**Comment by kosz78** [comment]
Yes it is issues related the latest TypeScript 1.4 migration, will be fixed a soon

**Comment by kosz78** [comment]
Fixed in the latest release
