### ISSUE TITLE
'Building workspace' has encountered a problem.

### ISSUE THREAD

**Issue by AGBrown** [axmor/typecs#49]
I get an error when building a file in the root of the project directory:

```
Title: Problem Occurred
Message: 'Building Workspace' has encountered a problem.
    Errors occurred during the build
Details: Errors occurred during the build.
Errors running builder 'Typescript Project Builder' on project 'pouchdb.d.ts - local clone'.
Path must include project and resource name: /pouchdb.d.ts - local clone
```

![image](https://cloud.githubusercontent.com/assets/128166/7382661/32b491e4-ee0a-11e4-9001-f3b683743c82.png)

Environment:
Windows 8.1
Java 7u75
Project directory: `D:\dev\pouchdb.d.ts - local clone\`
Eclipse:
    eclipse.application=org.eclipse.ui.ide.workbench
    eclipse.buildId=4.4.2.M20150204-1700
    com.axmor.eclipse.typescript.feature (3.1.0.201502192009) "TypEcs - TypeScript IDE for Eclipse"

This is using the [project here](https://github.com/AGBrown/pouchdb.d.ts) (at commit 391fd00c) and the project file here ([gist](https://gist.github.com/AGBrown/a25dbd3e70327bdc41ca))

**Comment by AGBrown** [comment]
It is worth noting that `.d.ts` and `.ts` files in a subdirectory build just fine - it is just the files in the project root directory that do not build.

**Comment by kosz78** [comment]
Could you please try the latest development build from https://drone.io/github.com/axmor/typecs/files

**Comment by rpofuk** [comment]
Same problem here:

![image](https://cloud.githubusercontent.com/assets/2906197/9402476/2d854294-47de-11e5-8092-a306a2320ede.png)

```
java.lang.IllegalArgumentException: Path must include project and resource name: /elevator-view
    at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
    at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2075)
    at org.eclipse.core.internal.resources.Container.getFile(Container.java:192)
    at com.axmor.eclipse.typescript.builder.builder.TypescriptBuilder.getFileByPath(TypescriptBuilder.java:258)
    at com.axmor.eclipse.typescript.builder.builder.TypescriptBuilder.handleCompileResult(TypescriptBuilder.java:216)
    at com.axmor.eclipse.typescript.builder.builder.TypescriptBuilder.compileFile(TypescriptBuilder.java:194)
    at com.axmor.eclipse.typescript.builder.builder.TypescriptBuilder.build(TypescriptBuilder.java:114)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

![image](https://cloud.githubusercontent.com/assets/2906197/9402478/378a0aea-47de-11e5-98b2-fa7ec8f62c09.png)

![image](https://cloud.githubusercontent.com/assets/2906197/9402495/68c6b96e-47de-11e5-80db-ee6901e074c7.png)

Code I'm trying to compile:
![image](https://cloud.githubusercontent.com/assets/2906197/9402524/a4e86596-47de-11e5-9198-18c1ca7aba58.png)

A.ts

```
module com.a {
    import B = com.b.B;

    export class A extends B{        
        test() { 
            console.log("Test A");            
            var b = new B();
            console.log("Static: " + B.staticTest)
        }

        test2() {
            console.log("Test A2");
        }    
    }
}

function executeApp() {
    var c = new com.a.A();
    c.test();
}
```

B.ts

```
module com.b {    
   import A = com.a.A;

    export class B {
        public static staticTest = 1;

         //testA
        constructor() {
            console.log(A);
            var a = new A();
            a.test2();
        }

        test() {
            console.log("Test B");
        }
    }
}
```
