### ISSUE TITLE
BTreeMap$LeafNode cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by qc00** [axmor/typecs#71]
Version is 3.1.0 on Eclipse 4.5.0

```
An internal error occurred during: "Indexing TypeScript source files".

java.lang.ClassCastException: org.mapdb.BTreeMap$LeafNode cannot be cast to java.lang.Long
    at org.mapdb.BTreeMap$BTreeIterator.pointToStart(BTreeMap.java:883)
    at org.mapdb.BTreeMap$BTreeIterator.<init>(BTreeMap.java:851)
    at org.mapdb.BTreeMap$BTreeKeyIterator.<init>(BTreeMap.java:1036)
    at org.mapdb.BTreeMap.keyIterator(BTreeMap.java:1581)
    at org.mapdb.BTreeMap$KeySet.iterator(BTreeMap.java:1681)
    at com.google.common.collect.Iterables.tryFind(Iterables.java:671)
    at com.axmor.eclipse.typescript.core.index.TypeScriptIndexer.checkFile(TypeScriptIndexer.java:293)
    at com.axmor.eclipse.typescript.core.index.IndexJob$1.visit(IndexJob.java:71)
    at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:119)
    at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:83)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
    at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:122)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:93)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:51)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:116)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:104)
    at com.axmor.eclipse.typescript.core.index.IndexJob.run(IndexJob.java:65)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by kosz78** [comment]
Fixed in the latest release
