### ISSUE TITLE
File not found errors for files created after Eclipse was started

### ISSUE THREAD

**Issue by nhnb** [axmor/typecs#96]
When I edit a file, I get a lot of errors in console, saying that the file was not found. Theses errors do not have a  stack trace. When I try to use Ctrl+Space for auto complete,I get the following error. Auto complete is not working.

```
Command error Error: Could not find file: 'ts/sub/Subber.ts'.
    at getValidSourceFile (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/ts/typescriptServices.js:37373:23)
    at getCompletionData (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/ts/typescriptServices.js:37749:30)
    at Object.getCompletionsAtPosition (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/ts/typescriptServices.js:38170:34)
    at TSService.getCompletionsAtPosition (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/js/service.js:35:33)
    at Object.thrift.createServer.invoke (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/js/new_bridge.js:38:59)
    at TSBridgeServiceProcessor.process_invoke (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/js/gen-nodejs/TSBridgeService.js:262:19)
    at TSBridgeServiceProcessor.process (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/js/gen-nodejs/TSBridgeService.js:230:39)
    at /usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/js/thrift/server.js:55:21
    at Socket.<anonymous> (/usr/local/eclipse/plugins/com.axmor.eclipse.typescript.core_4.0.0.201508061529/lib/typescript-bridge/js/thrift/transport.js:191:5)
    at emitOne (events.js:90:13)
```

Despite the errors, the .js files are created in my output folder.

.settings/com.axmor.eclipse.typescript.bridge.prefs 

```
declaration=true
eclipse.preferences.version=1
mapRoot=
module=commonjs
noImplicitAny=false
noResolve=false
removeComments=false
source=ts
sourceMap=true
target=bin
targetRelativePathBasedOnSource=true
targetVersion=ES5

```

**Comment by nhnb** [comment]
The issue occurs only with files that have been created since Eclipse was started.

The "Could not find file" error is thrown in getValidSourceFile() within createLanguageService()  near line 37375 of typescriptService.js. program.getSourceFile() only knows about files that existed at the time Eclipse was started.

This seems to be the root cause of the auto complete issue.

**Comment by youssefgh** [comment]
hello is this plugin still supported ?
