### ISSUE TITLE
version='4.0.0.201603011122' Connection refused: connect

### ISSUE THREAD

**Issue by hookclaw** [axmor/typecs#99]
Was opened "www.ts".
Waiting about 30 seconds.
Error happend.

Eclipse : Version: Mars.2 (4.5.2) Build id: M20160212-1500
OS : Windows Vista 32bit Home edition
java.version=1.8.0_60
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) Client VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.60-b23

Id: com.axmor.eclipse.typescript, バージョン: 4.0.0.201603011122, ロケーション: reference:file:plugins/com.axmor.eclipse.typescript_4.0.0.201603011122.jar
Id: com.axmor.eclipse.typescript.builder, バージョン: 4.0.0.201603011122, ロケーション: reference:file:plugins/com.axmor.eclipse.typescript.builder_4.0.0.201603011122.jar
Id: com.axmor.eclipse.typescript.core, バージョン: 4.0.0.201603011122, ロケーション: reference:file:plugins/com.axmor.eclipse.typescript.core_4.0.0.201603011122/
Id: com.axmor.eclipse.typescript.debug, バージョン: 4.0.0.201603011122, ロケーション: reference:file:plugins/com.axmor.eclipse.typescript.debug_4.0.0.201603011122.jar
Id: com.axmor.eclipse.typescript.debug.ui, バージョン: 4.0.0.201603011122, ロケーション: reference:file:plugins/com.axmor.eclipse.typescript.debug.ui_4.0.0.201603011122.jar
Id: com.axmor.eclipse.typescript.editor, バージョン: 4.0.0.201603011122, ロケーション: reference:file:plugins/com.axmor.eclipse.typescript.editor_4.0.0.201603011122.jar
Id: com.axmor.eclipse.typescript.ui, バージョン: 4.0.0.201603011122, ロケーション: reference:file:plugins/com.axmor.eclipse.typescript.ui_4.0.0.201603011122.jar

**Windows Task Manager**

> PID : 828
> CMD : node.exe D:\pleiades\eclipse\plugins\com.axmor.eclipse.typescript.core_4.0.0.201603011122\lib\typescript-bridge\js\new_bridge.js src=C:/WS1/sandboxTS serv=true port=51739 log=debug

**netstat -nao**

> PID  : 828  nothing
> port : 51739  nothing

**C:/WS1/.metadata/.log**

> !ENTRY com.axmor.eclipse.typescript.bridge 4 0 2016-04-26 11:03:56.306
> !MESSAGE java.net.ConnectException: 接続が拒否されました: 接続
> !STACK 0
> org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused: connect
>     at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
>     at com.axmor.eclipse.typescript.core.internal.TypeScriptBridge.run(TypeScriptBridge.java:145)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: java.net.ConnectException: Connection refused: connect
>     at java.net.DualStackPlainSocketImpl.connect0(Native Method)
>     at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
>     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
>     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
>     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
>     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
>     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>     at java.net.Socket.connect(Socket.java:589)
>     at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
>     ... 4 more

**Comment by hookclaw** [comment]
1. Task killed. PID : 828 
2. CMD execute : node.exe D:\pleiades\eclipse\plugins\com.axmor.eclipse.typescript.core_4.0.0.201603011122\lib\typescript-bridge\js\new_bridge.js src=C:/WS1/sandboxTS serv=true port=51739 log=debug
3. Console output.

> .....
> .....
> .....
> .....
> host.readDir: TS/work/js/client
> host.readDir: views
> host.readDir: views/file_viewer
> host.readDir: views/phpts
> host.readDir: views/test
> host.getLocalizedDiagnosticMessages

**Comment by p-kudrin** [comment]
Could you try this develop version? https://drone.io/github.com/axmor/typecs/files/src/com.axmor.eclipse.typescript.repository/target/com.axmor.eclipse.typescript.repository-4.0.0-SNAPSHOT.zip

**Comment by hookclaw** [comment]
```
-- エラー詳細 --
日付: Sat May 07 08:41:29 JST 2016
メッセージ: java.net.ConnectException: 接続が拒否されました: 接続
重大度: エラー
プロダクト: Eclipse プラットフォーム 4.5.2.v20160212-1500 (org.eclipse.platform.ide)
プラグイン: com.axmor.eclipse.typescript.bridge
セッション・データ:
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=ja_JP
Framework arguments:  -product -product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product -data file:/C:/WS1/ -product

例外スタック・トレース:
org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused: connect
    at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
    at com.axmor.eclipse.typescript.core.internal.TypeScriptBridge.run(TypeScriptBridge.java:145)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
    ... 4 more

```

```
-- エラー詳細 --
日付: Sat May 07 08:44:04 JST 2016
メッセージ: Unexpected runtime error while computing a text hover
重大度: エラー
プロダクト: Eclipse プラットフォーム 4.5.2.v20160212-1500 (org.eclipse.platform.ide)
プラグイン: org.eclipse.jface.text
セッション・データ:
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=ja_JP
Framework arguments:  -product -product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product -data file:/C:/WS1/ -product

例外スタック・トレース:
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Cannot write to null outputStream
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at com.axmor.eclipse.typescript.core.internal.TypeScriptBridge.invokeBridgeMethod(TypeScriptBridge.java:285)
    at com.axmor.eclipse.typescript.core.internal.TypeScriptBridge.invokeBridgeMethod(TypeScriptBridge.java:243)
    at com.axmor.eclipse.typescript.core.internal.TypeScriptAPIImpl.getSignature(TypeScriptAPIImpl.java:119)
    at com.axmor.eclipse.typescript.editor.hover.TypeScriptTextHover.getHoverInfo(TypeScriptTextHover.java:67)
    at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:168)
Caused by: org.apache.thrift.transport.TTransportException: Cannot write to null outputStream
    at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:142)
    at org.apache.thrift.protocol.TBinaryProtocol.writeI32(TBinaryProtocol.java:178)
    at org.apache.thrift.protocol.TBinaryProtocol.writeString(TBinaryProtocol.java:201)
    at org.apache.thrift.protocol.TBinaryProtocol.writeMessageBegin(TBinaryProtocol.java:110)
    at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
    at com.axmor.eclipse.typescript.core.internal.TSBridgeService$Client.send_invoke(TSBridgeService.java:83)
    at com.axmor.eclipse.typescript.core.internal.TSBridgeService$Client.invoke(TSBridgeService.java:72)
    at com.axmor.eclipse.typescript.core.internal.TypeScriptBridge.invokeBridgeMethod(TypeScriptBridge.java:279)
    ... 4 more

```

I think I try to change to  `Visual Studio Code` to update the OS.
Thank you.
